# Generated by Django 3.0.2 on 2022-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='predictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('time', models.TimeField()),
                ('label', models.CharField(max_length=50)),
            ],
        ),
    ]
